export const armSubCats = {
  ALLARMS: 'All Arm Symptoms',
  SHOULDER: 'Shoulder Symptoms',
  ARMPIT: 'Armpit Symptoms',
  UPPERARM: 'Upper Arm Symptoms',
  ELBOW: 'Elbow Symptoms',
  FOREARM: 'Forearm Symptoms',
  WRIST: 'Wrist Symptoms',
  HAND: 'Hand Symptoms',
  FINGERS: 'Fingers Symptoms',
}

export const allArmsSymptoms = [
  'able to bend wrist backwards',
  'abnormal creases in palm',
  'adson manuever positive',
  'arm edema (swelling), unilateral',
  'arm has no muscle tone',
  'arm is numb',
  'arm jerking',
  'arm muscles shrinking',
  'arm or leg is numb',
  'arm pain',
  'arm pain when moving arms',
  'arm swelling',
  'arm tremor',
  'arm/hand pain due to median nerve problem',
  'arms able to bend',
  'arms and hands tender to touch',
  'arms are weak',
  'arms turning blue',
  'arms turning red',
  'asterixis',
  'axillary lymph node enlargement',
  'axillary lymph node tenderness',
  'bicep shaking',
  'biceps and triceps hyperreflexia',
  'biceps hyporeflexia',
  'blue nails',
  'brachymesophalangia, fifth finger',
  'brown nails',
  'burning feeling in arm or leg',
  'burning feeling in hand',
  'camptodactyly',
  "can't move arm or leg",
  "can't recognize fingers",
  "can't straighten bent finger(s)",
  "can't write",
  'clinodactyly',
  'cold hand',
  'compressed nerve in wrist/hand',
  'crackling sound when moving wrist',
  'cramp in my palm',
  'curved fingers',
  'darkened skin on elbow',
  'darkened skin on knuckle(s)',
  'darkening skin on armpit',
  'discolored fingertip',
  'double jointed hand',
  "durkan's compression test positive",
  'elbow bones out of place',
  'elbow pain',
  'enlarged fingertips',
  'extremity pulse absence, upper',
  'fatty yellowish skin rash on palms',
  'finger blood vessel obstruction',
  'finger chewing',
  'finger deformity',
  'finger shaking',
  'finger(s) are swollen',
  'finger(s) feel stiff',
  'finger(s) feel tender',
  'finger(s) feel tight',
  'finger(s) hurts',
  'finger(s) locks in place',
  'finger(s) point to little finger side of hand',
  'finger(s) really sensitive to touch',
  'finger(s) too cold',
  'finger(s) turn red',
  'finger(s) turns blue',
  'fingernail(s) hurt',
  'fingertip tender to touch',
  'firm lump in arm pit',
  'fist clenching',
  'flaky tough or thick skin on palms of hand',
  'forearm feels more sensitive',
  'forearm feels weak',
  'forearm hurts',
  'forearm is angled away from the body',
  'forearm itches',
  'forearm turning up',
  'forearm turns in',
  'freckles in armpit',
  'half of nail is white and other half is deeper pink',
  'hand asterixis',
  'hand changing colors',
  'hand cramping at night',
  'hand hurts',
  'hand hurts when moving',
  'hand is numb',
  'hand is red',
  'hand is turned towards little finger',
  'hand muscle weakness',
  'hand or arm shaking when performing task',
  'hand shaking',
  'hand shortness',
  'hand smallness',
  'hand spiderlike',
  'hand swelling',
  'hand wringing',
  'hands move too slowly',
  'hands shake or twitch when resting',
  'hard bumps on finger(s)',
  'hives on hand',
  'hoffman sign positive',
  'humeral swelling, lower',
  'infected lump or sore on hand',
  'itchy palms',
  'knuckle deformity',
  'knuckle joint on hand hurts',
  'large hands',
  'large shoulder vein',
  'large veins on arm',
  'left arm hurts',
  'left arm is numb',
  'left shoulder hurts',
  'losing armpit hair',
  'lump in armpit that doesn\'t move',
  'lump in shoulder',
  'lump on forearm',
  'milkmaid\'s grip',
  'muscle spasm in arm only',
  'muscles on outside of palm are shrinking or thinning',
  'nail(s) are blue',
  'one arm weak',
  'open sore(s) on arm',
  'open sore(s) on finger(s)',
  'open sore(s) on fingertip(s)',
  'open sore(s) on hand',
  'open sore(s) on palm',
  'pain in arm or leg',
  'pain in fluid-filled sac of shoulder below collar bone',
  'pain in fluid-filled sac, upper outer part of shoulder',
  'pain in palm of hand',
  'painful nodules in armpits',
  'pale arms',
  'pale finger(s)',
  'palm area under thumb is flat',
  'palm is swollen',
  'palms sweating more',
  'paralyzed arm',
  'paralyzed arm with no muscle tone',
  'passive painful arc maneuver',
  'pea-sized lump under skin on arm',
  'pea-sized lump under skin on finger(s)',
  'pea-sized lump(s) on palm of hand',
  'peeling hands',
  'phalen\'s maneuver positive',
  'pill rolling tremor',
  'rash limited to armpit',
  'rash limited to hand',
  'rash limited to legs or arms',
  'rash limited to palm',
  'rash on hand',
  'red bump(s) on elbow',
  'red flaky rash limited to palms or soles',
  'red palms',
  'regression or loss of acquired purposeful hand skills',
  'right shoulder hurts',
  'shoulder girdle fascia thickening',
  'shoulder girdle muscle weakness',
  'shoulder granule',
  'shoulder muscle pain',
  'shoulder muscle twitching',
  'shoulder pain',
  'shoulder shrug sign',
  'shoulder stiffness',
  'shoulder tender to touch',
  'shrinking or thinning muscles in hand',
  'single line that runs across the palm of hand',
  'skin on finger(s) is thick',
  'skin on palm peeling off',
  'smooth, soft palms',
  'spider veins in fingernails',
  'stiff arm or leg',
  'stiff arms',
  'stiff elbow',
  'stiff hands',
  'subacromial bursal tenderness',
  'subdeltoid bursal tenderness',
  'swollen knuckles',
  'swollen shoulder',
  'syndactyly',
  'tenderness lateral epicondyle',
  'thin arms',
  'thumb absence',
  'thumb hurts',
  'thumb microdactyly',
  'thumb spatulate',
  'thumb synostosis',
  'thumb, distal phalynx, shortness',
  'thumb, triphalangeal',
  'tingling and prickling in finger(s)',
  'tingling or pricking of arm',
  'tingling or prickling in forearm',
  'tingling or prickling in hand',
  'tingling or prickling of palm',
  'tough or thick skin on base of wrist',
  'tough or thick skin on palms of hand',
  'triceps hyporeflexia',
  'trouble moving hands',
  'trouble speaking or talking',
  'unequal arm blood pressure',
  'unusually short fingers',
  'upper arm pain',
  'upper extremity deformity',
  'upper extremity hypertension',
  'upper extremity hyporeflexia',
  'upper extremity shortness',
  'upper extremity span increase',
  'upper extremity spasticity',
  'very little armpit hair',
  'weak finger(s)',
  'weak hand grip',
  'weak thumb muscle',
  'wide flat hand',
  'wrist flexor muscle atrophy',
  'wrist hurts when moved',
  'wrist is red',
  'wrist is swollen on thumb side',
  'wrist muscle weakness',
  'wrist pain',
  'wrist stiffness',
  'wrist swelling',
  'wrist tenderness, radial',
  'wristdrop',
  'yellow palms'
]

export const shoulderSymptoms = [
  'large shoulder vein',
  'lump in shoulder',
  'shoulder girdle fascia thickening',
  'shoulder girdle muscle weakness',
  'shoulder granule',
  'shoulder muscle pain',
  'shoulder muscle twitching',
  'shoulder shrug sign',
  'shoulder tender to touch',
  'subacromial bursal tenderness',
  'subdeltoid bursal tenderness',
  'swollen shoulder'
]

export const armpitSymptoms = [
  'axillary lymph node enlargement',
  'axillary lymph node tenderness',
  'darkening skin on armpit',
  'firm lump in arm pit',
  'freckles in armpit',
  'losing armpit hair',
  'lump in armpit that doesn\'t move',
  'painful nodules in armpits',
  'rash limited to armpit',
  'very little armpit hair'
]

export const upperArmSymptoms = [
  'bicep shaking',
  'biceps and triceps hyperreflexia',
  'biceps hyporeflexia',
  'humeral swelling, lower',
  'triceps hyporeflexia',
  'upper arm pain'
]

export const elbowsSymptoms = [
  'darkened skin on elbow',
  'elbow bones out of place',
  'elbow pain',
  'flaky bump(s) limited to elbows or knees',
  'forearm is angled away from the body',
  'red bump(s) on elbow',
  'single flaky raised skin patch on elbows or knees',
  'stiff elbow',
  'tenderness lateral epicondyle'
]
export const forearmSymptoms = [
  'forearm feels more sensitive',
  'forearm feels weak',
  'forearm hurts',
  'forearm itches',
  'forearm turning up',
  'forearm turns in',
  'lump on forearm',
  'tingling or prickling in forearm'
]

export const wristSymptoms = [
  'able to bend wrist backwards',
  'crackling sound when moving wrist',
  "phalen's maneuver positive",
  'tough or thick skin on base of wrist',
  'wrist flexor muscle atrophy',
  'wrist hurts when moved',
  'wrist is red',
  'wrist is swollen on thumb side',
  'wrist muscle weakness',
  'wrist pain',
  'wrist stiffness',
  'wrist swelling',
  'wrist tenderness, radial',
  'wristdrop'
]

export const handSymptoms = [
  'abnormal creases in palm',
  'arm/hand pain due to median nerve problem',
  'asterixis',
  'brachymesophalangia, fifth finger',
  'brown nails',
  'burning feeling in hand',
  'camptodactyly',
  'can\'t write',
  'cold hand',
  'compressed nerve in wrist/hand',
  'cramp in my palm',
  'curved fingers',
  'darkened skin on knuckle(s)',
  'double jointed hand',
  'durkan\'s compression test positive',
  'fatty yellowish skin rash on palms',
  'fist clenching',
  'flaky tough or thick skin on palms of hand',
  'hand asterixis',
  'hand changing colors',
  'hand cramping at night',
  'hand hurts',
  'hand hurts when moving',
  'hand is numb',
  'hand is red',
  'hand is turned towards little finger',
  'hand muscle weakness',
  'hand or arm shaking when performing task',
  'hand shaking',
  'hand shortness',
  'hand smallness',
  'hand swelling',
  'hand wringing',
  'hands move too slowly',
  'hives on hand',
  'infected lump or sore on hand',
  'itchy palms',
  'knuckle deformity',
  'knuckle joint on hand hurts',
  'large hands',
  'milkmaid\'s grip',
  'muscles on outside of palm are shrinking or thinning',
  'open sore(s) on hand',
  'open sore(s) on palm',
  'pain in palm of hand',
  'palm area under thumb is flat',
  'palm is swollen',
  'palms sweating more',
  'pea-sized lump(s) on palm of hand',
  'peeling hands',
  'rash limited to hand',
  'rash limited to palm',
  'rash on hand',
  'red flaky rash limited to palms or soles',
  'red palms',
  'shrinking or thinning muscles in hand',
  'single line that runs across the palm of hand',
  'skin on palm peeling off',
  'smooth, soft palms',
  'stiff hands',
  'stiff knuckles in hands or toes',
  'swollen knuckles',
  'tingling or prickling in hand',
  'tough or thick skin on palms of hand',
  'trouble moving hands',
  'trouble speaking or talking',
  'weak hand grip',
  'wide flat hand',
  'yellow palms'
]

export const fingersSymptoms = [
  'blue nails',
  "can't recognize fingers",
  "can't straighten bent finger(s)",
  'clinodactyly',
  'discolored fingertip',
  'enlarged fingertips',
  'finger blood vessel obstruction',
  'finger chewing',
  'finger deformity',
  'finger shaking',
  'finger(s) are swollen',
  'finger(s) feel stiff',
  'finger(s) feel tender',
  'finger(s) feel tight',
  'finger(s) hurts',
  'finger(s) locks in place',
  'finger(s) point to little finger side of hand',
  'finger(s) really sensitive to touch',
  'finger(s) too cold',
  'finger(s) turn red',
  'finger(s) turns blue',
  'fingernail(s) hurt',
  'fingertip tender to touch',
  'half of nail is white and other half is deeper pink',
  'hand spiderlike',
  'hard bumps on finger(s)',
  'hoffman sign positive',
  'nail loss',
  'nail not growing the way it should',
  'nail pulling away from cuticle',
  'nail(s) are blue',
  'open sore(s) on finger(s)',
  'open sore(s) on fingertip(s)',
  'pale finger(s)',
  'pea-sized lump under skin on finger(s)',
  'skin on finger(s) is thick',
  'spider veins in fingernails',
  'syndactyly',
  'thumb absence',
  'thumb hurts',
  'thumb microdactyly',
  'thumb spatulate',
  'thumb synostosis',
  'thumb, distal phalynx, shortness',
  'thumb, triphalangeal',
  'tingling and prickling in finger(s)',
  'unusually short fingers',
  'weak finger(s)',
  'weak thumb muscle'
]