export const buttocksSubCats = {
  ALLBUTTOCKS: 'All Buttocks Symptoms',
  HIP: 'Hip Symptoms',
  RECTUM: 'Rectum Symptoms',
}

export const allButtocksSymptoms = [
  'anal bleeding',
  'anal bulla, hemorrhagic',
  'anal canal induration',
  'anal fistula',
  'anal inflammation',
  'anal mass tenderness',
  'anal nodule',
  'anal sphincter spasm',
  'anal ulceration',
  'anus, imperforate',
  'blood in poop',
  'bright red blood in poop',
  'bulky poop',
  'butt feels numb',
  'butt hurts',
  'butt pain',
  "can't poop completely",
  'clay colored poop',
  'clotted swollen veins near anus',
  'constipation',
  'diarrhea',
  'diarrhea after meals',
  'diarrhea at night',
  'discharge from rectum smells bad',
  'feels like need to poop all the time',
  'fluid leaking from butt',
  'gassy',
  'gluteal crease low, unilateral',
  'green colored poop',
  'hard stool',
  'hemorrhoid',
  'infected lump or sore on tailbone',
  'inflamed tailbone',
  'infrequent bowel movements',
  'itchy anus',
  'itchy buttocks',
  'large crack between or under butt cheeks',
  'large stool',
  'levator ani spasm',
  'lump on butt',
  'melanosis coli',
  'mucous leaking from butt',
  'mucus on poop',
  'oily greasy looking poop',
  'pain during pooping',
  'poop is thin',
  'poop leaking',
  'poop smells bad',
  'pus coming from butt',
  'pus-filled bump(s) in buttocks hair follicle(s)',
  'rash limited to anus',
  'rash limited to buttocks',
  'rectal fissure',
  'rectal fistula',
  'rectal mass',
  'rectal mucous membrane discoloration, orange',
  'rectal pain',
  'rectal tenderness',
  'rectal ulceration',
  'rectal urine',
  'rectoperineal fistula',
  'rectum paralyzed',
  'rectum protrudes out anus',
  'red bumps around hair follicles on buttocks',
  'relaxed anal sphincter',
  'sacroileitis',
  'sacroiliac tenderness',
  'sciatic nerve pain',
  'sciatic nerve tenderness',
  'severe constipation',
  'stool backed up or blocked',
  'straining during bowel movement',
  'swollen vein protrudes from anus',
  'tarry stool',
  'tingling and numbness on butt',
  'tissue death of anus',
  'wart on butt',
  'yellow colored poop',
]

export const hipSymptoms = [
  'acetabular dysplasia',
  'bend at hip',
  'coxa valga',
  'coxa vara',
  'difficulty getting up from a chair',
  'greater tuberosity tenderness',
  'hip deformity',
  'hip feels like it pops out of socket',
  'hip feels stiff',
  'hip hurts',
  'hip is swollen',
  'hip muscle is weak',
  'hip tenderness',
  'hurts to walk',
  'ischial tuberosity tenderness',
  'pelvic muscles are tight',
  'pelvic muscles feel weak',
  'pelvic smallness',
  'pelvis tilted',
  'pelvis wide',
]

export const rectumSymptoms = [
  'anal bleeding',
  'anal bulla, hemorrhagic',
  'anal canal induration',
  'anal fistula',
  'anal inflammation',
  'anal mass tenderness',
  'anal nodule',
  'anal sphincter spasm',
  'anal ulceration',
  'anus, imperforate',
  'blood in poop',
  'bright red blood in poop',
  'bulky poop',
  'butt hurts',
  "can't poop completely",
  'clay colored poop',
  'clotted swollen veins near anus',
  'constipation',
  'feels like need to poop all the time',
  'gassy',
  'green colored poop',
  'hard stool',
  'hemorrhoid',
  'infrequent bowel movements',
  'itchy anus',
  'large stool',
  'melanosis coli',
  'mucus on poop',
  'oily greasy looking poop',
  'pain during pooping',
  'poop is thin',
  'poop leaking',
  'poop smells bad',
  'rash limited to anus',
  'rectal fissure',
  'rectal fistula',
  'rectal mass',
  'rectal mucous membrane discoloration, orange',
  'rectal tenderness',
  'rectal ulceration',
  'rectal urine',
  'rectoperineal fistula',
  'rectum protrudes out anus',
  'relaxed anal sphincter',
  'stool backed up or blocked',
  'swollen vein protrudes from anus',
  'tarry stool',
  'tissue death of anus',
  'wart on butt',
  'yellow colored poop',
]