export const headSubCats = {
  ALLHEAD: 'All Head Symptoms',
  SCALP: 'Scalp Symptoms',
  FOREHEAD: 'Forehead Symptoms',
  EYES: 'Eye Symptoms',
  NOSE: 'Nose Symptoms',
  EARS: 'Ear Symptoms',
  FACE: 'Face Symptoms',
  MOUTH: 'Mouth Symptoms',
  JAW: 'Jaw Symptoms',
}

export const allHeadSymptoms = [
  'anosognosia',
  'can\'t handle noise',
  'can\'t keep my head up',
  'can\'t remember',
  'cognitive impairment',
  'comprehension impairment',
  'confusion',
  'decline in memory or other thinking skills',
  'deformed or misshapen head',
  'delusions',
  'dizziness',
  'dull headache',
  'face and head feel sensitive in places',
  'fatigue',
  'feel pressure in head',
  'feeling of pressure in head',
  'fever',
  'fits of rage',
  'flattened area along the back of skull',
  'frightening thoughts',
  'half of face doesn\'t sweat',
  'head bouncing',
  'head congestion',
  'head growing slowly',
  'head injury',
  'head is too narrow',
  'head jerking',
  'head shaking',
  'head size is getting bigger',
  'head swelling',
  'head tilts to side',
  'headache',
  'headache behind ears',
  'headache in back of head',
  'headache on one side of head',
  'headache on temples',
  'headache that just started',
  'headache with sex',
  'impulsive behavior',
  'insomnia',
  'macrocephaly',
  'memory loss',
  'migraine headache',
  'nasal sinus pain',
  'open sore(s) on head',
  'pea-sized lump(s) on head',
  'really sleepy during day',
  'repeated headaches',
  'sense of impending doom',
  'sensorineural hearing loss',
  'severe headache',
  'small head',
  'some face and head muscles are paralyzed or unable to move',
  'sudden severe headache',
  'temples are sunken in',
  'temporal artery nodularity',
  'temporal artery pulse absence',
  'temporal artery tenderness',
  'temporal artery thickening',
  'temporal artery vasodilation',
  'tension headache',
  'throbbing headache',
  'tingling or prickling feeling around face and head',
  'trouble concentrating',
  'trouble with short term memory',
  'vertigo',
  'waking up with headache',
  'weak muscles in face'
]

export const scalpSymptoms = [
  'baby\'s soft spot is bulging',
  'baby\'s soft spot is still open',
  'baby\'s soft spot is sunken',
  'baby\'s soft spot is tight',
  'bald spots (hair)',
  'blond hair',
  'bulging out of back of skull',
  'clear ringing sound note when tapping the skull',
  'clogged pores in bald spots',
  'complete loss of hair over entire body',
  'completely bald',
  'cranial osteoma',
  'craniosynostosis',
  'cut on scalp',
  'dandruff',
  'deformed forehead',
  'dry scalp',
  'dull sound when tapping the skull',
  'early grey hair',
  'enlarged vein on scalp',
  'flaky or greasy skin on scalp',
  'follicular scarring',
  'forehead bones breaking down',
  'forehead sticks out',
  'hair dryness',
  'hair getting straighter',
  'hair loss with crusty rash',
  'hair loss with scarring',
  'hair sparse',
  'head lice',
  'headache',
  'increased pressure in skull',
  'intracranial bruit',
  'itchy scalp',
  'long hair',
  'long nails',
  'losing hair',
  'losing hair in patch(es)',
  'low hairline',
  'lump on scalp',
  'male pattern baldness',
  'matted hair',
  'open pores in bald spots',
  'open sore(s) on scalp',
  'pointed head',
  'pulling out hair',
  'pus-filled bump(s) in bald spot',
  'pus-filled bump(s) in scalp hair follicle(s)',
  'random hairs in bald patch(es)',
  'random white hairs in bald spots',
  'rash limited to scalp',
  'red bumps around hair follicles on scalp',
  'red hair',
  'red skin in bald areas',
  'redness and dry scaly skin with hair loss',
  'scalp feels overly sensitive',
  'scalp feels warm',
  'scalp hurts',
  'scalp tender to touch',
  'scalp vessel pulse increase',
  'seams of skull separate',
  'shiny bald head',
  'shiny scalp',
  'skin on scalp feels thinner',
  'soft skull',
  'swollen scalp',
  'tough or thick skin on scalp',
  'white hair',
  'widespread loss of hair',
]

export const foreheadSymptoms = [
  'can\'t pay attention',
  'confused thinking and reduced awareness of your environment',
  'enlarged vein on forehead',
  'fatigue',
  'fever',
  'forehead is tender',
  'forehead sticks out',
  'hairy forehead',
  'hallucination',
  'headache',
  'headache in front of head',
  'high forehead',
  'inappropriate behavior',
  'lightheadedness',
  'paranoia',
  'wide forehead',
  'wrinkled forehead'
]

export const eyesSymptoms = [
  'argyll-robertson pupil',
  'astigmatism',
  'black eye',
  'black spots floating in my eye',
  'bleeding around the eye',
  'bleeding eyelid',
  'bleeding in eye',
  'bleeding in front part of eye',
  'blind spot',
  'blind spot that appears blank',
  'blind spot that appears dark',
  'blood vessels in colored part of eye',
  'blurry vision',
  'blurry vision in one eye',
  'brownish-yellowish ring around the color of eye',
  'bruising around eyes',
  'bugs in my eye',
  'bulging eyes',
  'burn to part of eye',
  'bushy eyebrows',
  'can\'t close eye all the way',
  'can\'t focus eyes',
  'can\'t look up',
  'can\'t move eyes to the side',
  'can\'t recognize things i see',
  'can\'t turn my eyes',
  'can\'t see far away',
  'can\'t see up close',
  'cataract',
  'central scotoma',
  'central vision loss',
  'chorioretinitis',
  'choroid coloboma',
  'choroiditis',
  'cloudy area on cornea',
  'color blindness',
  'conjunctival contracture',
  'conjunctival fold necrosis, yellow white',
  'conjunctival papillary flatness',
  'conjunctival papillary hardening',
  'conjunctival pseudomembrane',
  'conjunctival smoothness',
  'conjunctivitis, follicular',
  'constant red dry eyes',
  'corneal areflexia',
  'corneal contracture',
  'corneal dystrophy',
  'corneal protrusion',
  'cross eyed',
  'decreased tears',
  'decreased vision',
  'dilated pupil',
  'distorted vision',
  'double vision',
  'double vision in one eye',
  'downslanting palpebral fissues',
  'drooping eyelid',
  'drusen',
  'dry eyes',
  'enlarged brow ridge',
  'enlarged vein on clear part of eye',
  'extraocular muscle imbalance',
  'extraocular muscle weakness',
  'eye bleeds',
  'eye blinking',
  'eye color is changing to blue',
  'eye contact impairment',
  'eye discharge',
  'eye hurts',
  'eye hurts when i move it',
  'eye is burning',
  'eye is red and irritated',
  'eye not in normal position in socket',
  'eye opening is narrow',
  'eye pain',
  'eye socket hurts',
  'eye socket is sinking inward',
  'eye strain',
  'eye too large',
  'eye twitching',
  'eyeball is swollen',
  'eyebrow hair loss',
  'eyebrow lice',
  'eyebrow loss of color',
  'eyelid closes too slowly',
  'eyelid crusting and sticking together',
  'eyelid feels like it is burning',
  'eyelid feels scratchy',
  'eyelid feels thick',
  'eyelid flipped up',
  'eyelid folds inward',
  'eyelid granulation',
  'eyelid hurts',
  'eyelid is red and irritated',
  'eyelid pink gray',
  'eyelid pus',
  'eyelid tender to touch',
  'eyelid twitching',
  'eyelids feel hard',
  'eyelids feel heavy',
  'eyes are irritated',
  'eyes bulge out',
  'eyes don\'t move together',
  'eyes fixed on a single location',
  'eyes rolling back',
  'eyes tearing more',
  'eyes wide open',
  'eyesight getting worse',
  'eyesight worse in one eye',
  'feeling pressure below the eye',
  'flashing lights in vision',
  'flickering uncolored zig-zag lines in vision',
  'frequent squinting',
  'front part of eye is swollen',
  'front part of eye looks cloudy',
  'glaucoma',
  'grayish/brown spots on the outside of colored part of eye',
  'growth that looks like a yellow spot or bump on the eyeball',
  'hemianopia',
  'hole in colored part of eye',
  'hypopyon',
  'infected lump or sore on eyelid',
  'inner corner of eye is swollen',
  'intraocular pressure decrease',
  'intraocular pressure increase',
  'iridocyclitis',
  'iritis',
  'irritated eye',
  'itchy eye',
  'itchy eyelid',
  'keratitis',
  'lacrimal gland lobulation',
  'lacrimal sac inflammation',
  'large blister on the eye',
  'lateral vision loss',
  'lazy eye',
  'lens dislocation',
  'light hurts eyes',
  'little eyes',
  'losing eye color',
  'losing eyelashes',
  'loss of an area of vision',
  'loss of an area of vision in both eyes',
  'loss of an area of vision in one eye',
  'loss of color vision in one spot',
  'loss of eyelashes',
  'loss of vision in both eyes',
  'loss of vision in one eye',
  'lump in eye socket',
  'maculae ceruleae',
  'macular degeneration',
  'mucus coming from the eye',
  'no color in eye',
  'no peripheral vision',
  'not able to make tears',
  'nystagmus',
  'nystagmus latency',
  'nystagmus reversal',
  'nystagmus, fatigue',
  'nystagmus, rotary',
  'ocular cherry red spot',
  'one eye bulges',
  'one eye not turning',
  'one eye sees better than the other',
  'one eyelid swollen',
  'one or both eyes look downward',
  'one or both eyes look to the side',
  'open sore(s) on colored part of eye',
  'open sore(s) on eye',
  'open sore(s) on eyelid',
  'opening snap',
  'optic nerve atrophy',
  'optic neuritis',
  'pain around the eye',
  'pain behind the eye',
  'painful and weak eye movement',
  'papilledema',
  'part of outer layer of eye sticking to another part',
  'peripheral vision loss',
  'pink eye',
  'pinpoint pupils',
  'poor night vision',
  'prominent brow ridge',
  'pupil fixed',
  'pupil irregularity',
  'pupillary deformity',
  'pupillary inequality',
  'pupillary whiteness',
  'pus coming from the eye',
  'rash limited to eyelid',
  'red color blindness',
  'red eye',
  'red eyelid',
  'retinal angioid streaks',
  'retinal bleeding',
  'retinal coloboma',
  'retinal detachment',
  'retinal exudate',
  'retinal granuloma',
  'retinal opacity',
  'retinal pallor',
  'retinal pigmentation',
  'retinitis',
  'roth spots',
  'scar on clear part eye',
  'scar on the eye',
  'seeing halos of light around things',
  'severe eye pain',
  'single red eye',
  'skin and eyes more sensitive to sunlight',
  'skin folded over upper eyelid',
  'slower blinking',
  'small blister on eye',
  'small dot of light or zigzag shape in your vision',
  'small flat spots of loss of skin color',
  'something stuck inside the eye',
  'sore eye',
  'specks or spots in colored part of eye',
  'spider vein(s) in eye',
  'stye',
  'sunken eyes',
  'swelling around the eyes',
  'swollen eyelid',
  'swollen tear duct',
  'tear duct hurts',
  'tear duct is red',
  'tearing in one eye',
  'temporary vision loss',
  'things appear smaller than they are',
  'things in vision appear yellowish',
  'thinning eyebrows',
  'thinning eyelashes',
  'third nerve paralysis',
  'tiny red or purple spots limited to inside eye',
  'torn eyelid',
  'trouble looking up',
  'trouble moving eyes',
  'trouble opening eye',
  'tumor on one eye',
  'twitching of colored part of eye',
  'unable to see clearly',
  'uveitis',
  'uveitis, bilateral',
  'violet color to eyelid',
  'vision loss',
  'visual aura',
  'visual hallucination',
  'vitreous hemorrhage',
  'watery eyes',
  'white part of eye is black',
  'white part of eye is blue',
  'white part of eye is white',
  'white patch(es) around eye',
  'white, grey or blue ring seen around color part of eye',
  'whitish material on eyelid',
  'wideset eyes',
  'wrinkle between eyebrows',
  'yellow eyes',
  'yellow open sore(s) on eye',
  'yellow pea-sized lump(s) on eyelid'
]

export const noseSymptoms = [
  'along smile or laugh lines are red',
  'blockage in nose',
  'bloody nose',
  'boil on nose',
  'bridge of nose looks flat',
  'clear runny nose',
  'cleft nose',
  'dented nostril',
  'deviated septum',
  'dry nasal passages',
  'growth in nose',
  'hay fever',
  'head congestion',
  'high nose bridge',
  'hooked nose',
  'inside of nose is black',
  'inside of nose is red',
  'inside of nose is swollen',
  'irritated nose',
  'itchy nose',
  'low nose bridge',
  'nasal sinus draining',
  'nasal sinus feels full',
  'nasal sinus is blocked',
  'nasal sinus pain',
  'nasal sinus sore',
  'nose and throat are inflamed',
  'nose destruction',
  'nose discharge, foul smelling, unilateral',
  'nose discharge, purulent, unilateral',
  'nose feels like it is burning',
  'nose flares open',
  'nose getting bigger',
  'nose hair burned',
  'nose hurts',
  'nose is turned upward',
  'nose misshapen',
  'nose mucous membrane atrophy',
  'nose oral communication',
  'nose septum destruction',
  'nose septum necrosis',
  'nose septum perforation',
  'nose septum ulceration',
  'nose skin infected',
  'nose tender to touch',
  'nosebleed',
  'nostrils are very small',
  'nostrils tilt down',
  'open sore(s) on nose',
  'open sore(s) on the nostril',
  'postnasal drip',
  'pus coming out of nose',
  'red nose',
  'rounded nose',
  'runny nose',
  'shingles on tip of nose',
  'sinus pain or infection bridge of nose',
  'sinus ulceration',
  'sinusitis',
  'small nose',
  'smelling things that aren\'t there',
  'smelly, runny nose',
  'sneezing',
  'snotty, runny nose',
  'snout reflex',
  'stuffy nose',
  'stuffy nose',
  'swollen nose',
  'thin nose',
  'tingling or pricking of nose',
  'trouble smelling',
  'using decongestant nose drops',
  'wide nose'
]

export const earsSymptoms = [
  'big ears',
  'blocked ear',
  'bony area behind ear is infected with pus',
  'bony area behind ear is swollen',
  'bony area behind ear is tender',
  'bony growths in the ear',
  'bruising on skull behind the ear',
  'can\'t hear on one side',
  'conductive hearing loss',
  'constant ear ringing',
  'diagonal crease in ear lobe',
  'dry skin in ear',
  'ear bleeding',
  'ear cartilage is blue or black',
  'ear doesn\'t look right',
  'ear infection',
  'ear infection middle ear',
  'ear is red',
  'ear lesion, mucoid',
  'ear tender to touch',
  'ear wax blocking ear',
  'earache',
  'earlobe crease',
  'ears feel full',
  'ears set low',
  'fluid leaking from my ear',
  'hard lumps around joints',
  'headache behind ears',
  'hear crackling noises in my ears',
  'hearing is getting worse',
  'hearing things that aren\'t there',
  'hole in eardrum',
  'inner ear infection',
  'itchy ear',
  'large blister on eardrum',
  'large earlobes',
  'lump in front of ear',
  'lump on ear',
  'mastoid bruit',
  'mastoiditis',
  'middle ear infection',
  'otitis externa',
  'otitis interna',
  'outside of ear hurts',
  'pain in bony area behind ear',
  'pus coming from my ear',
  'rash limited to ear',
  'red and irritated swollen ear',
  'redness of skin on skull behind ear',
  'scaly or greasy skin on or behind ear',
  'single skin growth on ear lobe',
  'small ear',
  'small ear canal',
  'something is stuck in my ear',
  'swelling in front of ears',
  'swollen ear cartilage',
  'tough or thick skin around joints',
  'trouble hearing',
  'tympanic membrane bulging',
  'tympanic membrane hypomobile',
  'tympanic membrane inflammation',
  'tympanic membrane opaque',
  'tympanic membrane retraction',
  'tympanic membrane scarring',
  'very sensitive to noise',
  'very sensitive to sounds',
  'vestibular impairment',
  'whole ear swollen ear'
]

export const faceSymptoms = [
  'can\'t feel temperature on face',
  'can\'t move my face',
  'can\'t move my face well',
  'can\'t move one side of my face',
  'cheek bone pain',
  'cheek pain',
  'enlarged vein on face',
  'expressionless face',
  'face extremely thin and bony',
  'face feels full',
  'face feels numb',
  'face feels weak',
  'face hair turning white',
  'face hurts',
  'face is blotchy',
  'face is swollen',
  'face is turning blue',
  'face is yellow',
  'face misshapen',
  'face round',
  'face spasms when stimulated',
  'face sweats a lot',
  'face tender to touch',
  'face turns red when eating, drinking or exercising',
  'face turns reddish color',
  'face twitches',
  'face twitching',
  'facies coarse',
  'facies grotesque',
  'facies mongoloid',
  'facies triangular',
  'feels like air is under my face',
  'fragile or thin skin on face',
  'hair on face',
  'half of face is flushed',
  'horner syndrome',
  'huge cheek bones',
  'infected lump or sore on face',
  'itchy face',
  'limp muscle in face',
  'long face',
  'losing fat in face',
  'loss of facial hair',
  'lump on face',
  'nasal sinus pain',
  'no facial sweating',
  'numbness of face',
  'one side of face feels weak',
  'one side of face not the same as the other',
  'one side of my face hurts',
  'open sore(s) on face',
  'pale face',
  'pea-sized lump under skin on face',
  'pinched expression',
  'rash limited to face',
  'red face',
  'red flaky rash limited to smile or laugh lines',
  'red, swollen, runny nose',
  'rough hair on face',
  'sagging skin on face',
  'skin on face feels hard',
  'sore facial hair',
  'spider vein(s) on face',
  'stiff muscle in face',
  'thinning facial hair',
  'tingling or pricking face skin',
  'tingling or pricking on one side of face',
  'tingling or pricking skin of face',
  'trigeminal neuralgia',
  'trigeminal paralysis',
  'unibrow',
  'veins on face dilated',
  'weak muscles in face',
  'winking caused by jaw movement'
]

export const mouthSymptoms = [
  'area of mucus on tongue',
  'area of mucus on tongue',
  'area under tongue is swollen',
  'back of mouth is red',
  'bad breath',
  'black stuff coating tongue',
  'bleeding gums',
  'blisters on tongue',
  'breath has a fruity smell',
  'breath has a sweet and tarry smell',
  'breath smells like almonds',
  'breath smells like garlic',
  'breath smells like urine',
  'breath smells metallic',
  'broken speech pattern',
  'brown flat discolored spot(s) limited to lips',
  'buccal patch(es) mucus',
  'bulimia',
  'can\'t pucker lips',
  'can\'t speak',
  'canker sore',
  'chin recession',
  'cleft lip',
  'cleft palate',
  'cold sore',
  'corner of mouth hurts',
  'corner of mouth is sagging',
  'cough',
  'crack at the corner of mouth',
  'crack on tongue',
  'cracked lips',
  'crave salt',
  'damaged teeth enamel',
  'dehydration',
  'dental alveolar suppuration',
  'dental arch narrowness',
  'dental caries',
  'dentition delay',
  'denture pain',
  'diminished gag reflex',
  'drooling',
  'dry lips',
  'dry mouth',
  'dry tongue',
  'edentulous',
  'food doesn\'t taste good',
  'furry green coating on tongue',
  'geographic tongue',
  'gingival erythema',
  'gingival fistula',
  'gingival lead line, purple',
  'gingival leukoplakia',
  'gingival tenderness',
  'gingival ulceration',
  'gingival vesicle',
  'gingivitis',
  'gums hurt',
  'hives inside of mouth',
  'hives on lips',
  'hot food or liquids hurt tooth',
  'infected lump or sore on lip',
  'inflamed tongue',
  'inside of mouth is black',
  'inside of mouth is brown',
  'inside of mouth is red',
  'inside of mouth is white',
  'inside of mouth is yellow',
  'inside of mouth swollen',
  'interdental papillary ulceration',
  'involuntary jerky or fitful movement of tongue',
  'koplik spot',
  'large blister(s) in mouth',
  'large tongue',
  'lip chewing',
  'lip hurts',
  'lip is tingling or prickling',
  'lip pulled back',
  'lip tender to touch',
  'lip trembling',
  'lipoatrophy',
  'lips are thicker',
  'lips turning blue',
  'long groove between nose and lip',
  'lower lip droops',
  'lump on tongue',
  'mallampati grade i',
  'mallampati grade iii-iv',
  'malocclusion',
  'metal taste in mouth',
  'microdontia',
  'micrognathia',
  'molar loosening, deciduous',
  'more thirsty than usual',
  'mouth bleeding',
  'mouth breathing',
  'mouth burn',
  'mouth hurts',
  'mouth is sore',
  'mouth is swollen',
  'mouth itches',
  'mouth looks crooked',
  'mouth mucous membrane bleeding',
  'mouth mucous membrane ulceration',
  'mouth opened',
  'mouth tender to touch',
  'mouth wideness',
  'mucous membrane petechia',
  'mucous membrane scarring',
  'mute',
  'open sore(s) in mouth',
  'open sore(s) inside of cheek',
  'open sore(s) on back of mouth',
  'open sore(s) on inside of cheek',
  'open sore(s) on lip',
  'open sore(s) on roof of mouth',
  'open sore(s) on tongue',
  'orange tonsils',
  'pain in tooth socket',
  'palatal muscle weakness',
  'palatal paralysis',
  'palatal tremor',
  'pale around mouth',
  'pea-sized lump on tongue',
  'producing too much saliva',
  'pseudomembrane',
  'puckered lip',
  'raised skin patch(es) on tongue',
  'red bump(s) inside of cheek',
  'red irritated throat',
  'red lips',
  'red or purple flat spots on inside of cheeks',
  'red tonsil',
  'roof of mouth has high arch',
  'roof of mouth is inflamed',
  'roof of mouth is misshapen',
  'roof of mouth is numb',
  'roof of mouth is red',
  'roof of mouth narrow',
  'roof of mouth red',
  'roof of mouth swollen',
  'round ball in back of throat is out of place',
  'round ball in back of throat is swollen',
  'self induced vomiting',
  'severely bad breath',
  'short groove between nose and lip',
  'shrinking tongue',
  'skin sore(s) inside of mouth',
  'skin sore(s) on tonsil',
  'small blister on roof of mouth',
  'small bump on inside of cheek',
  'small bump(s) on back of mouth',
  'small flat red or purple spots on back of mouth',
  'small flat red or purple spots on round ball in back of throat',
  'small flat red or purple spots on tonsil',
  'small red spots on roof of mouth',
  'small white bump(s) on inside of cheek',
  'smooth groove between nose and lip',
  'snoring',
  'soft palate atrophy',
  'soft palate numbness',
  'soft palate paralysis',
  'soft palate swelling',
  'sores in or on side of mouth',
  'speech is slow',
  'spider vein(s) on roof of mouth',
  'stuff coats top of tongue',
  'stuttering',
  'swelling around the mouth',
  'swollen gums',
  'swollen lips',
  'swollen throat',
  'swollen tongue',
  'swollen tonsil on one side',
  'swollen tonsils',
  'tasting things that aren\'t there',
  'teeth do not fit well',
  'teeth grinding',
  'thin lips',
  'throat is dry',
  'thrush',
  'tingling or numbness around mouth',
  'tingling or pricking inside mouth',
  'tingling or pricking tongue',
  'tiny mouth',
  'tongue biting',
  'tongue blanching',
  'tongue feels like it is burning',
  'tongue glazing',
  'tongue has no grooves',
  'tongue hurts',
  'tongue infection',
  'tongue is more red than usual',
  'tongue is out of place',
  'tongue is weak',
  'tongue not normal size and shape',
  'tongue pushed out too far',
  'tongue quivers',
  'tongue trembling',
  'tonsil inflammation',
  'tonsil is out of place',
  'tonsillar leukoplakia',
  'tooth cold sensitivity',
  'tooth deformity',
  'tooth discoloration',
  'tooth enamel hypoplasia',
  'tooth enamel pitting',
  'tooth erosion',
  'tooth extraction',
  'tooth impaction',
  'tooth loose',
  'tooth loss',
  'tooth pegged',
  'tooth root defect',
  'tooth spacing irregularity',
  'toothache',
  'top lip hangs over',
  'trouble chewing',
  'trouble communicating',
  'trouble producing saliva',
  'trouble speaking',
  'trouble tasting',
  'tumor in mouth',
  'upper lip is swollen',
  'voice doesn\'t sound right',
  'vomiting blood',
  'white coating on tongue',
  'white rash on inside of mouth',
  'white rash on roof of mouth',
  'white skin sore(s) on back of mouth',
  'white skin sore(s) on round ball in back of throat',
  'whitish coating on tonsil',
  'yawning',
  'yellow skin sore(s) on back of mouth',
  'yellow skin sore(s) on uvul'
]

export const jawSymptoms = [
  'area under chin is hard',
  'beard lice',
  'cheek and jaw swollen',
  'cheek fullness',
  'cheek swelling',
  'chin thrusting',
  'clicking or popping sound from jaw',
  'enlarged jaw vein',
  'indentations going down cheek',
  'inflammation inside mouth',
  'jaw angle tenderness',
  'jaw deformity',
  'jaw hurts',
  'jaw induration',
  'jaw mass firmness',
  'jaw muscle spasm',
  'jaw muscle weakness',
  'jaw tremor',
  'lower jaw hurts',
  'lump on cheek',
  'lymph node under jaw enlarged',
  'mandibular degeneration',
  'mandibular osteoma',
  'mandibular swelling',
  'mandibular tenderness',
  'mandibular tumor',
  'muscle spasm in jaw',
  'pain in jaw when chewing',
  'parotid gland ulceration',
  'parotitis',
  'prominent jaw',
  'pus-filled bump(s) in beard hair follicle(s)',
  'red bumps around hair follicles in beard',
  'retrognathia',
  'small jaw',
  'submaxillary gland swelling',
  'swelling beneath lower jaw',
  'swelling inside mouth',
  'tumor on upper jaw',
  'upper jaw hurts',
  'upper jaw is large',
  'upper jaw is small'
]