export const legsSubCats = {
  ALLLEGS: 'All Legs Symptoms',
  THIGHS: 'Thighs Symptoms',
  HAMSTRING: 'Hamstring Symptoms',
  KNEE: 'Knee Symptoms',
  POPLITEAL: 'Popliteal Symptoms',
  SHIN: 'Shin Symptoms',
  CALF: 'Calf Symptoms',
  ANKLE: 'Ankle Symptoms',
  FOOT: 'Foot Symptoms',
  TOES: 'Toes Symptoms',
}

export const allLegsSymptoms = [
  'achilles areflexia',
  'always moving one of legs',
  'ankle is overly flexible',
  'ankle pain',
  'ankle redness',
  'ankle reflex decreased',
  'ankle swollen',
  'arthritis in ankle',
  'arthritis in big toe',
  'arthritis in big toe joint',
  'arthritis in the arch of foot',
  'back of knee hurts',
  'back of knee is swollen',
  'back of upper leg is weak',
  'ball of foot joint hurts when move',
  'big toe bends too far up',
  'big toe hurts',
  'big toe hurts when moving',
  'big toe is under the second toe',
  'big toe joint is stiff',
  'big toe joint is swollen',
  'big toe joint is tender to touch',
  'bottom of foot pain',
  'bottom of foot peeling',
  'bottom of foot red',
  'bottom of foot sweats more',
  'bottom of foot swelling',
  'bottom of foot yellow',
  'bruise on ankle',
  'burning feeling in arm or leg',
  'burning feeling on thigh',
  'calf muscle cramp',
  'calf muscle feels hard',
  'calf muscle is larger than normal',
  'calf pain',
  'calf swelling',
  'can feel small lump in knee',
  'can\'t feel hot or cold on thigh',
  'can\'t hold foot up',
  'can\'t move arm or leg',
  'can\'t move leg outward',
  'can\'t tell where my leg is',
  'can? walk normally',
  'charcot joint',
  'clubfoot',
  'clutton joints',
  'cramp in thigh muscle',
  'dahl\'s sign positive',
  'darkened skin on knee',
  'descending stairs difficulty',
  'difficulty climbing stairs',
  'dislocated knee',
  'drumstick lower extremity',
  'enlarged leg vein',
  'enlarged rounded toe',
  'extreme arch in foot',
  'extremity pulse absence, lower',
  'fat thigh',
  'feels like toe is burning',
  'flat feet',
  'foot changing color',
  'foot deformity',
  'foot feels cold',
  'foot feels hot or warm',
  'foot feels stiff',
  'foot feels weak',
  'foot hurts',
  'foot is numb',
  'foot is turned out',
  'foot is turned up',
  'foot muscle is thinning',
  'foot peeling',
  'foot pulse absence',
  'foot smallness',
  'foot turning blue',
  'foot turning red',
  'front of knee hurts',
  'front of knee is swollen',
  'genu valgum',
  'genu varum',
  'great toe metatarsophalangeal prominence',
  'great toe microdactyly',
  'great toe synostosis',
  'hard nodules on legs',
  'heel hurts',
  'heel is swollen',
  'heel is turning in',
  'heel is turning out',
  'heel spur',
  'heel tenderness',
  'hives on foot',
  'hoover sign',
  'hurts to kneel',
  'hurts to walk',
  'infected lump or sore on foot',
  'infected lump or sore on leg',
  'inflamed fluid sac in knee',
  'inside edge of knee is swollen',
  'itching thigh',
  'itchy foot',
  'joint fluid swelling of back off knee joint',
  'knee cracking when moving',
  'knee feels like it is slipping',
  'knee gets stuck when moving',
  'knee hurts',
  'knee instability',
  'knee is able to bend',
  'knee joint inflammation',
  'knee joint makes popping sounds',
  'knee tender to touch',
  'lachman test positive',
  'large feet',
  'large thigh muscle',
  'leg cramp',
  'leg hurts',
  'leg is swollen',
  'leg muscles are weak',
  'leg muscles shrinking',
  'leg pain with walking',
  'leg shaking',
  'leg turning blue',
  'legs are numb',
  'legs changing color',
  'legs pale',
  'legs too cold',
  'limping',
  'loss of coordination',
  'lower extremity adduction',
  'lower extremity deformity',
  'lower extremity granuloma',
  'lower extremity hypertension',
  'lower extremity hyporeflexia',
  'lower extremity longness',
  'lower extremity shortness',
  'lower extremity spasticity',
  'lump on ankle',
  'lump on knee',
  'lurching gait',
  'matles test positive',
  'mcmurray test positive',
  'metacarpal shortness',
  'movement of upper leg outward',
  'need to move legs',
  'no fat on legs',
  'numb thigh muscle',
  'one leg has weak muscles',
  'one leg is red',
  'one leg swollen',
  'open sore(s) on foot',
  'open sore(s) on leg',
  'open sore(s) on soles of feet',
  'outer side of knee hurts',
  'pain in arm or leg',
  'pain in the arch of foot',
  'pain in thigh',
  'pain on inside edge of knee',
  'pale toe',
  'paralysis of legs and lower body',
  'paralysis on both sides of body in legs',
  'paralyzed legs',
  'patellar tendon reflex absent',
  'patellar tendon reflex decreased',
  'patellar tendon reflex increased',
  'peroneal sign positive',
  'pes cavus',
  'pigeon toed',
  'plantar reflex, absent',
  'popping sound when turn thigh outward',
  'pulsating lump around knee',
  'pus-filled bump(s) in leg hair follicle(s)',
  'rash limited to between toes',
  'rash limited to feet',
  'rash limited to legs or arms',
  'rash limited to soles of feet',
  'red bumps around hair follicles on leg',
  'red or purple flat spots on leg',
  'red thigh',
  'reduced ankle-brachial index',
  'ridges on shin bone',
  'rocker bottom feet',
  'sharp forward bowing of shin',
  'shin hurts',
  'shuffling gait',
  'skinny legs',
  'stiff arm or leg',
  'stiff big toe',
  'stiff knee',
  'stiff legs',
  'straight lower extremity raising test positive',
  'swelling in the arch of foot',
  'swollen foot',
  'swollen knee',
  'systemic venous stasis',
  'tender calf muscle',
  'thigh muscle feels firm',
  'thigh muscle mass',
  'thigh twitching',
  'tibial bone mass',
  'tibial deformity',
  'tibial pulse absence',
  'tibial tuberosity tenderness',
  'tingling and prickling in toe',
  'tingling or pricking of leg',
  'tingling or prickling in foot',
  'toe angle cleft',
  'toe deformity',
  'toe pain',
  'toe pulse absence',
  'toe pulse weakness',
  'toe shortness',
  'tripping',
  'trochanter elevation',
  'trouble moving foot',
  'trouble moving knee',
  'trouble walking',
  'up-going toe',
  'varicose vein',
  'weak knee muscle',
  'weak thigh muscle',
  'weakness in lower legs'
]

export const thighSymptoms = [
  'burning feeling on thigh',
  "can't feel hot or cold on thigh",
  'cramp in thigh muscle',
  "dahl's sign positive",
  'fat thigh',
  'itching thigh',
  'large thigh muscle',
  'movement of upper leg outward',
  'numb thigh muscle',
  'pain in thigh',
  'popping sound when turn thigh outward',
  'red thigh',
  'thigh muscle feels firm',
  'thigh muscle mass',
  'thigh twitching',
  'weak thigh muscle'
]

export const hamstringSymptoms = [
  'back of upper leg is weak'
]

export const kneeSymptoms = [
  'back of knee hurts',
  'can feel small lump in knee',
  'clutton joints',
  'darkened skin on knee',
  'dislocated knee',
  'flaky bump(s) limited to elbows or knees',
  'front of knee hurts',
  'front of knee is swollen',
  'genu valgum',
  'genu varum',
  'hurts to kneel',
  'hurts to walk',
  'inflamed fluid sac in knee',
  'inside edge of knee is swollen',
  'knee cracking when moving',
  'knee feels like it is slipping',
  'knee gets stuck when moving',
  'knee hurts',
  'knee instability',
  'knee is able to bend',
  'knee joint inflammation',
  'knee joint makes popping sounds',
  'knee tender to touch',
  'lump on knee',
  'mcmurray test positive',
  'outer side of knee hurts',
  'pain on inside edge of knee',
  'patellar tendon reflex absent',
  'patellar tendon reflex decreased',
  'patellar tendon reflex increased',
  'pulsating lump around knee',
  'single flaky raised skin patch on elbows or knees',
  'stiff knee',
  'swollen knee',
  'tibial tuberosity tenderness',
  'trouble moving knee',
  'weak knee muscle'
]

export const poplitealSymptoms = [
  'back of knee is swollen',
  'joint fluid swelling of back off knee joint',
  'lachman test positive'
]

export const shinSymptoms = [
  'ridges on shin bone',
  'sharp forward bowing of shin',
  'tibial bone mass',
  'tibial deformity',
  'tibial pulse absence'
]

export const ankleSymptoms = [
  'achilles areflexia',
  'ankle pain',
  'ankle redness',
  'ankle reflex decreased',
  'ankle swollen',
  'arthritis in ankle',
  'bruise on ankle',
  'lump on ankle'
]

export const footSymptoms = [
  'ankle is overly flexible',
  'arthritis in big toe joint',
  'arthritis in the arch of foot',
  'ball of foot joint hurts when move',
  'big toe joint is stiff',
  'big toe joint is swollen',
  'big toe joint is tender to touch',
  'bottom of foot pain',
  'bottom of foot peeling',
  'bottom of foot red',
  'bottom of foot sweats more',
  'bottom of foot swelling',
  'bottom of foot yellow',
  'can\'t hold foot up',
  'charcot joint',
  'clubfoot',
  'enlarged rounded toe',
  'extreme arch in foot',
  'feels like toe is burning',
  'flat feet',
  'foot changing color',
  'foot deformity',
  'foot feels cold',
  'foot feels hot or warm',
  'foot feels stiff',
  'foot feels weak',
  'foot hurts',
  'foot is numb',
  'foot is turned out',
  'foot is turned up',
  'foot muscle is thinning',
  'foot peeling',
  'foot pulse absence',
  'foot smallness',
  'foot turning blue',
  'foot turning red',
  'heel hurts',
  'heel is swollen',
  'heel is turning in',
  'heel is turning out',
  'heel spur',
  'heel tenderness',
  'hives on foot',
  'infected lump or sore on foot',
  'itchy foot',
  'large feet',
  'matles test positive',
  'metacarpal shortness',
  'open sore(s) on foot',
  'open sore(s) on soles of feet',
  'pain in the arch of foot',
  'pale toe',
  'pes cavus',
  'pigeon toed',
  'plantar reflex, absent',
  'rash limited to feet',
  'rash limited to soles of feet',
  'rocker bottom feet',
  'stiff big toe',
  'swelling in the arch of foot',
  'swollen foot',
  'tingling and prickling in toe',
  'tingling or prickling in foot',
  'toe angle cleft',
  'toe deformity',
  'toe pulse absence',
  'toe pulse weakness',
  'toe shortness',
  'tripping',
  'trouble moving foot'
]

export const toesSymptoms = [
  'arthritis in big toe',
  'big toe bends too far up',
  'big toe hurts',
  'big toe hurts when moving',
  'big toe is under the second toe',
  'big toe joint is swollen',
  'big toe joint is tender to touch',
  'great toe metatarsophalangeal prominence',
  'great toe microdactyly',
  'great toe synostosis',
  'nail loss',
  'nail not growing the way it should',
  'nail pulling away from cuticle',
  'rash limited to between toes',
  'stiff knuckles in hands or toes',
  'toe pain',
  'up-going toe'
]